apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-contour-cluster-issuer
spec:
  acme:
    email: cdelashmutt@vmware.com
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: us-east-2
          hostedZoneID: Z08415692IPTOH7IE83R
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-cert
  namespace: default
spec:
  commonName: "*.aws-work.grogscave.net"
  dnsNames:
  - "*.aws-work.grogscave.net"
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: default-cert
  subject:
    organizations:
    - vmware
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: default-cert
  namespace: default
spec:
  toNamespaces:
  - '*'
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: default-cert
  namespace: default
spec:
  delegations:
  - secretName: default-cert
    targetNamespaces:
    - "*"
