apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  annotations:
    kapp.k14s.io/delete-strategy: orphan
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::537807987484:role/worker.4811654495416222692.eks.tmc.cloud.vmware.com
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - eks-console-dashboard-full-access-group
      - system:masters
      rolearn: arn:aws:iam::537807987484:role/PowerUser
      username: cloudgate-poweruser
