apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: appsso-starter-java
  namespace: dev
spec:
  classRef:
    name: sso
  parameters:
    redirectPaths:
      - /login/oauth2/code/appsso-starter-java
    workloadRef:
      name: appsso-starter-java
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: appsso-starter-java
  namespace: dev
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: live-update
      value: "true"
  serviceClaims:
    - name: appsso-starter-java
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: appsso-starter-java
  source:
    git:
      ref:
        branch: main
      url: https://github.com/cdelashmutt-pivotal/appsso-starter-java
